version: '3.8'

services:
  backend:
    build:
      context: ./plump
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    env_file:
      - ./plump/.env
    #depends_on:
    #  - db

  frontend:
    build:
      context: ./project-management-ui
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
